set(_CATKIN_CURRENT_PACKAGE "pnp_ros")
set(pnp_ros_MAINTAINER "Luca Iocchi <iocchi@dis.uniroma1.it>")
set(pnp_ros_DEPRECATED "")
set(pnp_ros_VERSION "0.0.0")
set(pnp_ros_BUILD_DEPENDS "actionlib" "pnp_msgs" "roscpp" "rospy")
set(pnp_ros_RUN_DEPENDS "actionlib" "pnp_msgs" "roscpp" "rospy")
set(pnp_ros_BUILDTOOL_DEPENDS "catkin")